global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_andreev'
