version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: "${USER_NAME}/ui:$VER_UI"
    ports:
      - ${UI_PORT}:${REDDIT_PORT}/tcp
    networks:
      - ui
  post:
    image: ${USER_NAME}/post:latest
    networks:
      - reddit
      - ui
  comment:
    image: ${USER_NAME}/comment:latest
    networks:
      - reddit
      - ui

volumes:
  post_db:

networks:
  reddit:
  ui:
