version: '3.3'
services:

 ui:
   command: 'puma --debug -w 2'
   volumes:
     - "./ui:/app"

 comment:
   command: 'puma --debug -w 2'
   volumes:
     - "./comment:/app"

 post:
   volumes:
     - "./post-py:/app"


